# This docker-compose.yml file is used to build and test quickly
# a specific version of Dolibarr.
#
# Before build, define the variable DOLI_VERSION as following:
# $ export DOLI_VERSION=19.0.3
# And then, you can run :
# $ docker-compose up
#
# OR run the script ./test.sh dolversion [phpversion]
# sudo ./test.sh develop
# sudo ./test.sh 19.0.3  8.2
#  
# More information about Docker-compose : https://docs.docker.com/compose/

services:
    cron:
        build:
            context: ./docker-compose-links/${DOLI_VERSION}${PHP_VERSION}
        image: dolibarr/dolibarr:${DOLI_VERSION}${PHP_VERSION}
        environment:
            DOLI_CRON: 1
            DOLI_CRON_KEY: mycronsecurekey
            DOLI_CRON_USER: admintest
            DOLI_INSTANCE_UNIQUE_ID: myinstanceuniqueid
            DOLI_DB_USER: ${DOLI_DB_USER}
            DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD}
            DOLI_DB_HOST: ${DOLI_DB_HOST}
            DOLI_DB_NAME: ${DOLI_DB_NAME}
            DOLI_ADMIN_LOGIN: "admintest"
            DOLI_ADMIN_PASSWORD: "admintest"
            DOLI_URL_ROOT: "http://0.0.0.0:81"
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        networks:
            - external-pod

    web:
        build:
            context: ./docker-compose-links/${DOLI_VERSION}${PHP_VERSION}
        image: dolibarr/dolibarr:${DOLI_VERSION}${PHP_VERSION}
        volumes:
            - ./.volumes/dolibarr/custom:/var/www/html/custom
            - ./.volumes/dolibarr/documents:/var/www/documents
        environment:
            DOLI_INIT_DEMO: 1
            DOLI_DB_USER: ${DOLI_DB_USER}
            DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD}
            DOLI_DB_HOST: ${DOLI_DB_HOST}
            DOLI_DB_NAME: ${DOLI_DB_NAME}
            DOLI_ADMIN_LOGIN: "admintest"
            DOLI_ADMIN_PASSWORD: "admintest"
            DOLI_URL_ROOT: "http://0.0.0.0:81"
            DOLI_INSTANCE_UNIQUE_ID: myinstanceuniqueid
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        ports:
            - "81:80"
        networks:
            - external-pod
